# Generated by Django 5.2.4 on 2025-08-06 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['-source_date']},
        ),
        migrations.AddField(
            model_name='event',
            name='risk_rating',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='impacted_lines',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='event',
            name='risk_taxonomy_lv2',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='event',
            name='risk_taxonomy_lv3',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='source',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='theme',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_themes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='theme',
            name='risk_rating',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='useraccesslog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='tracker_cat_name_102452_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-date_identified'], name='tracker_eve_date_id_c7c751_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='tracker_eve_status_954236_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['risk_rating'], name='tracker_eve_risk_ra_2633a9_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['-source_date'], name='tracker_sou_source__47d951_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['source_type'], name='tracker_sou_source__7addd3_idx'),
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['-created_at'], name='tracker_the_created_f11c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['risk_rating'], name='tracker_the_risk_ra_509560_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccesslog',
            index=models.Index(fields=['-login_time'], name='tracker_use_login_t_397665_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccesslog',
            index=models.Index(fields=['user'], name='tracker_use_user_id_689cf7_idx'),
        ),
    ]
