# Generated by Django 5.2.4 on 2025-08-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_source_options_event_risk_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('NEWS', 'NEWS'), ('REPORT', 'REPORT'), ('INTERNAL_DOC', 'INTERNAL_DOC'), ('LEGAL', 'LEGAL '), ('OTHER', 'OTHER')], default='OTHER', max_length=50),
        ),
    ]
