# Generated by Django 5.2.4 on 2025-08-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_risktaxonomylv2_risktaxonomylv3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='potential_impact',
            field=models.CharField(choices=[('ESCALATING', 'Risk is Escalating'), ('MAINTAINING', 'Risk is Maintaining'), ('DECREASING', 'Risk is Decreasing')], default='MAINTAINING', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='risk_rating',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('NEWS', 'News'), ('REPORT', 'Report'), ('INTERNAL_DOC', 'Internal Document'), ('LEGAL', 'Legal '), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
