# Generated by Django 5.2.4 on 2025-08-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_event_potential_impact_alter_event_risk_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='potential_impact_notes',
            field=models.TextField(blank=True, verbose_name='Potential Impact Notes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='potential_impact',
            field=models.CharField(choices=[('ESCALATING', 'Risk is Escalating'), ('MAINTAINING', 'Risk is Maintaining'), ('DECREASING', 'Risk is Decreasing')], default='MAINTAINING', max_length=20, verbose_name='Potential Impact Trend'),
        ),
    ]
