# Generated by Django 5.2.4 on 2025-08-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_event_potential_impact_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='potential_impact',
            field=models.CharField(blank=True, choices=[('ESCALATING', 'Risk is Escalating'), ('MAINTAINING', 'Risk is Maintaining'), ('DECREASING', 'Risk is Decreasing')], max_length=20, null=True, verbose_name='Potential Impact Trend'),
        ),
        migrations.AlterField(
            model_name='event',
            name='potential_impact_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Potential Impact Notes'),
        ),
    ]
