# Generated by Django 5.2.4 on 2025-08-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_event_potential_impact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='risk_taxonomy_lv1',
            field=models.JSONField(default=list),
        ),
    ]
