# Generated by Django 5.2.4 on 2025-08-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_event_risk_taxonomy_lv1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='potential_impact',
        ),
        migrations.RemoveField(
            model_name='event',
            name='potential_impact_notes',
        ),
        migrations.AddField(
            model_name='source',
            name='potential_impact',
            field=models.CharField(blank=True, choices=[('ESCALATING', 'Escalating'), ('MAINTAINING', 'Maintaining'), ('DECREASING', 'Decreasing')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='potential_impact_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('HORIZON SCANNING', 'Horizon Scanning'), ('TRANSITION TO KNOWN RISK', 'Transition to known risk'), ('UNDER MONITORING', 'Under monitoring')], max_length=50),
        ),
    ]
