# Generated by Django 5.2.4 on 2025-08-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_remove_event_potential_impact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('DOC', 'DOC'), ('EMAIL', 'Email')], default='OTHER', max_length=50),
        ),
    ]
