# Generated by Django 5.2.4 on 2025-08-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_source_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('DOC', 'DOC'), ('EMAIL', 'Email'), ('PDF', 'PDF')], default='OTHER', max_length=50),
        ),
    ]
