# Generated by Django 5.2.4 on 2025-08-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_source_source_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='change_impact',
        ),
    ]
