# Generated by Django 5.2.4 on 2025-08-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_remove_source_change_impact'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
