# Generated by Django 5.2.4 on 2025-08-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_ensure_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('LINK', 'Link'), ('FILE', 'File')], default='FILE', max_length=10),
        ),
    ]
