# Generated by Django 5.2.4 on 2025-08-29 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_alter_source_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('LINK', 'Link'), ('FILE', 'File'), ('MIXED', 'Mixed')], default='FILE', max_length=10),
        ),
        migrations.CreateModel(
            name='SourceFileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sources/%Y/%m/%d/')),
                ('replaced_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('replaced_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_history', to='tracker.source')),
            ],
            options={
                'ordering': ['-replaced_at'],
            },
        ),
    ]
