# Generated by Django 5.2.4 on 2025-08-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_alter_source_source_type_sourcefileversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='risk_rating',
            field=models.CharField(choices=[('low', 'Low'), ('MEDIUM', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20),
        ),
    ]
