# Generated by Django 5.2.4 on 2025-09-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_alter_theme_risk_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='risk_rating',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20),
        ),
    ]
