# Generated by Django 5.2.4 on 2025-09-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_alter_theme_risk_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
